language: cpp
compiler:
  - gcc

addons:
  postgresql: "9.1"

before_script:
  - psql -c "CREATE USER tarantool WITH PASSWORD 'tarantool';" -U postgres
  - psql -c "CREATE DATABASE tarantool;" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE tarantool TO tarantool;" -U postgres
  - export PG='127.0.0.1:5432:tarantool:tarantool:tarantool'

install:
  - uname -a
  - lsb_release -c -s
  - curl http://tarantool.org/dist/public.key | sudo apt-key add -
  - echo "deb http://tarantool.org/dist/master/ubuntu/ `lsb_release -c -s` main" | sudo tee -a /etc/apt/sources.list.d/tarantool.list
  - sudo apt-get update > /dev/null
  - sudo apt-get -q install tarantool tarantool-dev
  - sudo apt-get -q install libpq-dev

script:
  - mkdir ./build && cd ./build && cmake .. -DCMAKE_BUILD_TYPE=RelWithDebugInfo
  - make
  - make test
